blueprint:
  name: Aqara switch binary_sensor
  description: Bind action to Aqara switch
  domain: automation
  input:
    switch_id:
      name: Binary sensor entity
      description: The binary_sensor used to trigger the automation
      selector:
        entity:
          domain: binary_sensor
    alert:
      name: Wake
      description: Actions to run when cube wakes up (idle and you tap it)
      default: []
      selector:
        action: {}
    tap_twice:
      name: Double Tap
      description: Actions to run when cube is tapped twice (hold it with your hands and tap it twice the table)
      default: []
      selector:
        action: {}
    move:
      name: Move
      description: Actions to run when cube is moved (slide in any direction)
      default: []
      selector:
        action: {}
    free_fall:
      name: Drop
      description: Actions to run when cube is dropped (throw in the air and catch)
      default: []
      selector:
        action: {}
    shake_air:
      name: Shake
      description: Actions to run when cube is shaked (hold in your hands and shake)
      default: []
      selector:
        action: {}
    flip90:
      name: Flip 90ยบ
      description: Actions to run when cube is flipped 90 degrees (flipped to any side)
      default: []
      selector:
        action: {}
    flip180:
      name: Flip 180ยบ
      description: Actions to run when cube is flipped 180 degrees (flipped to the previous bottom side)
      default: []
      selector:
        action: {}
    rotate_right:
      name: Rotate Right
      description: Actions to run when cube is rotated right (turned clockwise)
      default: []
      selector:
        action: {}
    rotate_left:
      name: Rotate Left
      description: Actions to run when cube is rotated left (turned counter clockwise)
      default: []
      selector:
        action: {}
variables:
  action: '{{ trigger.to_state.state }}'
trigger:
  - platform: state
    entity_id: !input switch_id
condition: []
action:
  - choose:
      - conditions:
          - "{{ action == 'wakeup' }}"
        sequence: !input "alert"
      - conditions:
          - "{{ action == 'tap' }}"
        sequence: !input "tap_twice"
      - conditions:
          - "{{ action == 'slide' }}"
        sequence: !input "move"
      - conditions:
          - "{{ action == 'fall' }}"
        sequence: !input "free_fall"
      - conditions:
          - "{{ action == 'shake' }}"
        sequence: !input "shake_air"
      - conditions:
          - "{{ action == 'flip90' }}"
        sequence: !input "flip90"
      - conditions:
          - "{{ action == 'flip180' }}"
        sequence: !input "flip180"
      - conditions:
          - "{{ action == 'rotate' }}"
          - condition: numeric_state
            entity_id: !input switch_id
            attribute: angle
            above: '0'
        sequence: !input "rotate_right"
      - conditions:
          - "{{ action == 'rotate' }}"
          - condition: numeric_state
            entity_id: !input switch_id
            attribute: angle
            below: '0'
        sequence: !input "rotate_left"
    default: []
mode: queued
max_exceeded: silent
