blueprint:
  name: Xiaomi Aqara Wireless Wall Switch Double
  description: Bind action to Aqara Wireless Wall Switch Double
  domain: automation
  input:
    left_switch_id:
      name: Left Switch
      description: The left binary_sensor used to trigger the automation
      selector:
        entity:
          domain: binary_sensor
    right_switch_id:
      name: Right Switch
      description: The right binary_sensor used to trigger the automation
      selector:
        entity:
          domain: binary_sensor
    both_switch_id:
       name: Both Switches
      description: The left and right binary_sensor used to trigger the automation
      selector:
        entity:
          domain: binary_sensor
    single_left:
      name: Left Single Click
      description: Actions to run when cube is flipped 90 degrees (flipped to any side)
      default: []
      selector:
        action: {}
    flip180:
      name: Flip 180ยบ
      description: Actions to run when cube is flipped 180 degrees (flipped to the previous bottom side)
      default: []
      selector:
        action: {}
    move:
      name: move
      description: Actions to run when cube is moved (slide in any direction)
      default: []
      selector:
        action: {}
    tap_twice:
      name: Double Tap
      description: Actions to run when cube is tapped twice (hold it with your hands and tap it twice the table)
      default: []
      selector:
        action: {}
    shake_air:
      name: Shake
      description: Actions to run when cube is shaked (hold in your hands and shake)
      default: []
      selector:
        action: {}
    free_fall:
      name: Drop
      description: Actions to run when cube is dropped (throw in the air and catch)
      default: []
      selector:
        action: {}


mode: single
max_exceeded: silent

trigger:
- platform: event
  event_type: xiaomi_aqara.click
  event_data:
    entity_id: !input 'left_switch_id'
- platform: event
  event_type: xiaomi_aqara.click
  event_data:
    entity_id: !input 'right_switch_id'
- platform: event
  event_type: xiaomi_aqara.click
  event_data:
    entity_id: !input 'both_switch_id'

action:
- choose:
  - conditions: '{{ trigger.event.data.click_type == ''single'' }}'
    sequence: !input 'single'
  - conditions: '{{ trigger.event.data.click_type == ''double'' }}'
    sequence: !input 'double'
  - conditions: '{{ trigger.event.data.click_type == ''long'' }}'
    sequence: !input 'long'
  - conditions: '{{ trigger.event.data.click_type == ''both'' }}'
    sequence: !input 'both'
  - conditions: '{{ trigger.event.data.click_type == ''double_both'' }}'
    sequence: !input 'double_both'
  - conditions: '{{ trigger.event.data.click_type == ''long_both'' }}'
    sequence: !input 'long_both'
